.\" Copyright (c) 2025 Christopher Leyon                   -*- mode: nroff -*-
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright notice,
.\"    this list of conditions, and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright notice,
.\"    this list of conditions, and the following disclaimer in the documentation
.\"    and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd $Mdocdate$
.Dt M2 1
.Os
.Sh NAME
.Nm m2
.Nd Line-oriented macro processor
.Sh SYNOPSIS
.Nm
.Op Ar name=value ...
.Op Ar file ...
.Sh DESCRIPTION
.Nm
is a line-oriented macro processor, a
.Qq little brother
to the
.Xr m4 1
macro processor found on Unix systems.
It is based on an earlier program, m1, written by Jon Bentley.
Like other macro processors,
the program can perform several functions, including:
.Bl -enum
.It
Define and expand macros.
Macros have two parts, a name and a body.
All occurrences of a macro's name are replaced with the macro's body.
Macro expansion may include parameters.
Short macros can be defined on the command line by using the form
.Ql NAME=VAL ,
or
.Ql NAME=
to define with empty value.
.It
Include files.  Special include directives in a file are
replaced with the contents of the named file.
Includes can
be nested, with one included file including another.
Included files are processed for macros.
.It
Conditional text inclusion and exclusion.
Different parts of the text can be included in the final output, often
based upon whether a macro is or is not defined.
.It
Comments are removed from the output.
.Ql @comment
commands appear on a line of their own and are dropped from the output.
.Ql @rem ...@
macros are embedded in the input text and produce no output.
Use
.Ql @ignore
for a multi-line comment.
.It
Manage multiple output data streams with diversions.
Different streams may be saved to different files.
.El
.Pp
.Nm
does not scan
.Qq tokens
or replace unadorned text: macro
substitution must be explicitly requested by enclosing the macro
name in
.Qq @
characters.
Thus, any occurrence of
.Ql @name@
in the input is replaced in the output by the corresponding value.
To compensate for the burden of having to manually invoke
macro expansion, there is conversely no need to
.Qq quote
identifiers to protect against unwanted or inadvertent replacement,
which, depending upon the insistence of
.Em other
macro processors, may
present quite a challenge.
Substitutions can occur multiple times in a line.
.Pp
.Em Example :
.Bd -literal -offset indent -compact
@define Condition under
You are clearly @Condition@worked.
\ \ \ => You are clearly underworked.
.Ed
.Pp
No white space is allowed between
.Qq @
and the name, so a lone at\&-sign does not trigger macro processing in any way.
Thus, a line like
.Dl 100 dollars @ 5% annual interest.
is completely benign.
.Pp
Using the same character to delimit both the beginning and end of macro
invocations was a conscious design decision by m1's author, but it
presents challenges when attempting to parse more advanced syntax, such
as invoking macros in a nested fashion.
It is difficult to distinguish, purely lexically:
.Bd -literal -offset indent -compact
This is @one and 2@ AND ALSO @three and 4@.
This is @mid mySym @myBegPos1 Field1@ myLen@.
.Ed
To alleviate scanning ambiguities, any characters enclosed in
at\&-sign braces
.Qq @{...}
will be recursively scanned and expanded.
Thus
.Dl @data_list[@{my_key}]@
uses the value in
.Va my_key
to look up data from the array
.Va data_list .
The text between the braces is implicitly interpreted as if it
were surrounded by
.Qq @
characters, so
.Ql @{SYMBOL}
is correct.
The example shows the syntax when accessing an array element, but the
syntax is applicable generally.
The
.Qq @{...}
is required whenever you invoke macros inside other macros, and failure
to do so will result in obscure and hard\&-to-debug errors.
.Ss Commands
Control commands
.Po
such as
.Ql @if ,
.Ql @define ,
etc
.Pc
are distinguished by an
.Qq @
as the first character at the beginning of a line.
They consume the entire line.
Some commands have a
.Qq silent
alternate form, distinguished by a leading
.Qq s
in the command name, which prints fewer error messages or performs some
slightly altered function.
For example, the silent variant to include a file is
.Ql @sinclude .
.Pp
The following table lists control commands to
evaluate, control, or define macros for subsequent processing:
.Pp
.\" This table could use a little formatting TLC...
.Bl -tag -width @if(_not)_defined -offset indent
.It @append NAME TEXT
Add TEXT to an already defined NAME.
If NAME is a Symbol, TEXT is textually appended to its definition.
If NAME is a List, TEXT is added as the next element.
.It @array ARR
Declare ARR to be an Array.
See also
.Va @list .
.It @break
Interrupt execution of enclosing loop.
@break is only valid inside a @for, @foreach, or @while block.
.It @case NAME [PREAMBLE ...] [@of TEXT ...] [@otherwise ...] @endcase
Evaluate value of NAME, comparing it with
each successive @of TEXT.
If a matching @of branch is found, execute the preamble (if any) and the
of\&-branch text and commands.
If no @of text matches, use text from @otherwise block if present.
Execution of the @otherwise block does
.Em not
execute the preamble.
(The purpose of the preamble is to provide "boiler-plate" header text for
known cases.
The text and commands of the @otherwise block are expected
to compensate for the lack of a preamble.)
.It @cleardivert [N ...]
Clear stream(s) specified by N.
If no arguments are provided then all streams are cleared.
See the
.Sx Streams and Diversions
section.
.It @comment [TEXT]
Comment; ignore line.  Also @@, @c, @;, and @#.
.Ql @comment ,
.Ql @c ,
and
.Ql @@
must be followed by whitespace in order to be recognized as comment commands.
.Ql @;
and
.Ql @#
are recognized as comments whenever they appear in columns 1 and 2.
.It @continue
Continue next iteration of enclosing loop.
@continue is only valid inside a @for, @foreach, or @while block.
.It @data LIS ... @enddata
Store all lines until
.Ql @enddata
into list
.Va LIS .
Any previously existing list entries are deleted.
LIS must declared with
.Va @list .
See also
.Va @filedata .
.It @debug [TEXT]
If debugging, send TEXT to the debug file.
See also
.Va __DEBUG__ .
.It @decr NAME [N]
Subtract N (default 1) from an already defined NAME.  See note at @incr.
.It @default NAME VAL
Like @define, but no\&-op if NAME already defined.
.It @define NAME [TEXT]
Set value of NAME to TEXT.
If TEXT is missing, a value of 1 is assumed.
See also
.Va @null .
.It @divert [N]
Divert subsequent text to stream N.
Default 0 resets to standard output.
If N is negative, text is discarded.
See the
.Sx Streams and Diversions
section.
.It @dump [WHAT] [FILE]
Output names and definitions to FILE.
WHAT can be one of "symbols", "sequences", "commands", "names",
or an integer, which is assumed to be a block number.
.\"   "@dump blocks" also works (poorly) and is deliberately undocumented.
If WHAT is omitted, "symbols" is assumed.
If FILE is omitted, output is sent to
.Va __DEBUGFILE__ .
.It @dumpall WHAT [FILE]
Like @dump but include System symbols.
.It @dumpdef [SYM ...]
Output definition of SYM to
.Va __DEBUGFILE__ .
More than one symbol may be listed.
If no symbols are specified, all symbols are dumped.
.It @echo [TEXT]
Send TEXT to standard error.
Also called @errprint.
.Ql @warn
is similar, but adds the current file name and line number to output.
Variant
.Ql @secho
does not automatically add a newline to output.
.It @else
Switch to the alternate condition branch of an @if block.
Only one @else statement is allowed per @if block.
.It @endcase
Indicate the end of a @case structure.
Also called @esac thanks to Algol\ 68.
.It @endcmd
Indicate the end of a @newcmd definition.
.It @enddata
Indicate the end of a @data block.
Also called @eod.
.It @endif
Indicate the end of an @if or @unless condition block.
Also called @fi, keeping the dream alive.
.It @endlongdef
Indicate the end of a multi-line @longdef.
.It @endwhile
Indicate the end of a @while or @until loop.
Also called @wend, by few.
.It @error [TEXT]
Send TEXT to standard error; exit code 2.
Any diverted streams are discarded, although any wrapped text is evaluated.
Variant
.Ql @serror
prints only TEXT, omitting file and line number information, for
complete control over error messages.
.It @esyscmd CMDLINE ...
Execute CMDLINE in a subshell.
Standard output is captured into the output stream as normal.
Standard input is set to
.Pa /dev/null ,
but standard error is not modified.
The command's exit code is saved in
.Va __SYSVAL__ .
.It @eval TEXT
Parse and evaluate TEXT as a command.
.It @exit [N]
Immediately stop parsing; exit with status N.
If N is omitted, the default value is 0.
Negative values or values greater than 126 are changed to 1.
If N is non-zero, diverted streams are discarded.
Commands deferred with @wrap are processed regardless of N value.
.It @filedata LIS FILE
Read each line from FILE into list LIS.
Any previously existing list entries are deleted before reading file contents.
Variant
.Ql @sfiledata
does not print an error message if FILE does not exist.
LIS must be declared as a list, therefore user code must say
.Ql @list LIS
before @filedata can be used.
See also
.Va @data .
.It @filedefine NAME FILE
Read FILE contents to define NAME.
This is not intended to be a full\&-blown file inputter (use @filedata
for that) but rather just to read short snippets like a file path
or username.
Multi-line values are accepted but the final
trailing newline, if any, is stripped.
Variant
.Ql @sfiledefine
does not print an error message if FILE does not exist.
See also
.Va @define .
.It @for VAR START END [INCR] ... @next VAR
Execute a loop with VAR taking on successive
integer values specified by START and END.
Default INCR is 1.
.It @foreach VAR ARR|LIS ... @next VAR
Execute a loop with VAR taking on successive values of
.Em keys
to an array or list.
NOTE: Different Awk implementations may return array keys in differing order.
However, lists and data created with
.Ql @data
or
.Ql @filedata
are guaranteed to return their integer indices in numerical order.
.It @if EXPR ... [@else ...] @endif
Include subsequent lines of text if boolean expression is True.
If EXPR is a simple NAME, check if NAME is True.
See section
.Sx Boolean Expressions .
.It @ignore PATTERN
Discard input until a line that matches regular expression PATTERN is found.
.It @include FILE
Read and process contents of FILE.
Variant
.Ql @sinclude
does not print an error message if FILE does not exist.
See also
.Va @paste .
.It @incr NAME [N]
Add N (1) to an already defined NAME.
@incr and @decr may be used on both symbols and sequences.
Note: Unlike m4, @incr modifies the named symbol and produces no expansion output.
.It @initialize NAME VAL
Like @define, but error if NAME already defined.
.It @input [NAME]
Read a single line from keyboard to define NAME.
No prompt is issued; if you want one, use @echo.
If NAME is omitted, value is stored in symbol
.Va __INPUT__ .
.It @list LIS
Declare LIS to be a List.
See also
.Va @array .
.It @literal PATTERN
Read and print input literally, without interpretation, until line that
matches regular expression PATTERN.
.It @local NAME
Declare NAME as a symbol local to the current namespace.
.It @longdef NAME ... @endlongdef
Set value of NAME to <...> (all lines until @endlongdef).
.It @newcmd NAME ... @endcmd
Create a user command NAME (lines until @endcmd).
.It @next VAR
Continue execution of next iteration of enclosing @for or @foreach loop.
.It @nextfile
Ignore remainder of current file and resume processing with the next file.
.It @null NAME
Set value of NAME to the empty string.
Note the difference between this command and
.Ql @define NAME
which sets the value of NAME to 1.
.It @of TEXT
Begin a new branch of an enclosing @case structure
matching TEXT at run time.
Every branch's TEXT label must be unique.
.It @otherwise
Begin a new branch of an enclosing @case structure
which is executed if no @of branch triggers.
Only one @otherwise branch is permitted per @case structure.
.It @paste FILE
Insert FILE contents literally, with no changes or macros.
Variant
.Ql @spaste
does not print an error message if FILE does not exist.
.It @readonly NAME
Make NAME unchangeable \(em cannot be undone.
.It @return
Cease execution of a user command.
@return is only valid inside a @newcmd definition.
.It @sequence ID ACTION [N]
Create and manage sequences.
See the
.Sx Sequences
section.
.It @shell PATTERN [PROG]
Evaluate input until PATTERN and send raw data to PROG.
Output stream is captured; shell exit status is stored in
.Va __SYSVAL__ .
If PROG is not specified, the value of symbol
.Va M2_SHELL
will be used if defined; if not, the value of environment variable
.Ev SHELL
will be used.
If also not defined, the value of
.Va __PROG__[sh]
will be used.
PROG should default to a reasonable shell, but might be overridden to
run other useful programs such as an alternative shell, an email message
reader, or /usr/bin/bc.
It must be a program that functions as a filter (in the Unix sense,
i.e., reading from standard input and writing to standard output).
Standard error is not redirected, so any errors will appear on the terminal.
.It @split NAME LIS [FS]
Split value of NAME into N individual fields, storing them in LIS elements 1..N.
Any previous entries in LIS are deleted.
If
.Va FS
is specified, use it as field separator.
If not and symbol
.Va __FS__
is defined, use its value as field separator.
If neither condition is true, use Awk's default
.Va FS ,
which means fields will be split on whitespace.
See also
.Va @join@ , @list .
.It @syscmd CMDLINE ...
Execute CMDLINE using Awk's system() function.
Standard output and standard error are both discarded.
The command's exit code is saved in
.Va __SYSVAL__ .
.It @tracemode [FLAG...]
With no arguments, reset trace flags to default value.
Preceding flag with
.Qq +
or
.Qq \-
will add to or remove from trace flags;
otherwise, overwrite trace flags with new value.
See also
.Va __TRACEMODE__ .
.It @traceoff [SYM ...]
Disable tracing for specified symbols.
If SYM is omitted, disable tracing for all symbols.
.It @traceon [SYM ...]
Enable tracing for specified symbols.
If SYM is omitted, enable tracing for all symbols.
See also
.Va __TRACE__ .
.It @typeout
Print remainder of input file literally; no macro processing will be done.
.It @undefine NAME
Remove definition of NAME.
Symbols can also be removed from the command line with
.Ql U=<symName>
.It @undivert [N ...] | N FILE
Inject stream N (default all) into current stream.
If no arguments are provided then all streams are injected.
With second form, stream N is output to FILE.
Undiverted streams are automatically cleared.
See the
.Sx Streams and Diversions
section.
.It @unless EXPR ... [@else ...] @endif
Include subsequent text if EXPR is False.
If EXPR is a simple NAME, check if NAME == 0 (or undefined).
See section
.Sx Boolean Expressions .
.It @until EXPR ... @endwhile
Repeatedly evaluate input lines while boolean expression is False
and stop when it becomes True.
.It @while EXPR ... @endwhile
Repeatedly evaluate input lines while boolean expression is True
and stop when it becomes False.
.It @wrap TEXT
Defer TEXT until m2 has processed all files and diversions and is about to exit.
Wrapped text will be evaluated as a command; output will occur after diverted streams, if any.
Wraps are always processed, even if @error or @exit commands are encountered.
.\"     An m2 internal panic() will exit immediately without processing wraps.
.El
.Ss Including Files
.Nm
can incorporate the contents of files into its data stream.
.Ql @include
retrieves and processes the file data for macros, while
.Ql @paste
reads the file contents with no modifications.
Attempting to
.Ql @include
or
.Ql @paste
a non-existent file results in an error.
However, if the
.Qq silent
variants
.Po
.Ql @sinclude ,
.Ql @spaste
.Pc
are used, no message is printed.
If @include or @paste cannot find the specified FILE in the current directory,
it will consult the include path which is initialized from the
.Ev M2PATH
environment variable.
Directories can be inserted into the include path by specifying
.Ql I=<directory>
on the command line.
Paths specified this way are examined before entries from M2PATH,
to allow run-specific overrides.
The include path is also used, if needed, for file names passed on the
command line.
.Ss Functions
Specifying more than one word between
.Qq @
characters, as in
.Dl @xxxx AAA BBB CCC@
is used as a crude form of function invocation.
Macros can expand positional parameters whose actual values will be
supplied when the macro is called.
The definition should refer to $1, $2, etc.
${1} also works, so ${1}1 is distinguishable from $11.
$0 refers to the name of the macro itself.
$# is replaced with the actual number of parameters provided.
$* expands to each given parameter, separated by a space character.
When a definition refers to a parameter which is not supplied, an empty
string will be used as a default value.
You may supply more parameters than needed; excess parameters are
simply ignored.
.Pp
.Em Example :
.Bd -literal -offset indent -compact
@define greet Hello, $1!  m2 sends you $0ings.
@greet world@
\ \ \ => Hello, world!  m2 sends you greetings.
.Ed
.Pp
.Em WARNING :
Parameters passed using this syntax are parsed by splitting on
white space.
This means that in:
.Dl @foo \[dq]a b\[dq] c@
foo is given three arguments, not two: '"a', 'b"', and 'c'.
To support parameters with embedded spaces, an alternate syntax
is supported:
.Dl @foo{a b}{c}@
will provide two arguments: 'a b' and 'c'.  In order for this syntax to
be recognized, there must be no whitespace between the function name and
the first open brace; and no text at all between the final closing brace
and the trailing
.Qq @ .
.Pp
.Em Example :
.Bd -literal -offset indent -compact
@define foo Arg1='$1' Arg2='$2' Arg3='$3'  narg=$#
@foo "a b" c@
@foo{a b}{c}@
@foo{a b}{c}{}@
\ \ \ => Arg1='"a' Arg2='b"' Arg3='c'  narg=3
\ \ \ => Arg1='a b' Arg2='c' Arg3=''  narg=2
\ \ \ => Arg1='a b' Arg2='c' Arg3=''  narg=3
.Ed
.Pp
The following definitions are recognized:
.Pp
.Bl -tag -width @right_SYM_[N]@ -offset indent
.It @basename SYM@
Base (file) name of SYM implemented in Awk, assuming Unix style path
separators.
See also
.Va @xbasename .
.It @boolval [SYM]@
Output a formatted representation of the truthiness of SYM.
If the argument is not a symbol, use its value as a boolean state.
If SYM is omitted entirely, return True or False with 50/50 chance.
See system symbols
.Va __FMT__[0] ,
.Va __FMT__[1] ,
and
.Va __STRICT__[bool] .
.It @center SYM [WIDTH]@
Center the value of SYM in a field of WIDTH columns.
If WIDTH is omitted, the value of
.Va __COLUMNS__
is used.
Strings longer than WIDTH are truncated as necessary.
Variant
.Ql @scenter@
does not truncate output.
.It @chr SYM@
Output character with ASCII code SYM.
.It @date@
Current date (format as __FMT__[date]).
See section
.Sx Dates and Times .
.It @dirname SYM@
Directory name of SYM implemented in Awk, assuming Unix style path
separators.
See also
.Va @xdirname .
.It @divlines STREAM@
Return the number of lines in STREAM, or zero if empty.
.It @dow [MJD | YYYY MM DD]@
Return the ISO day number corresponding to the date specified,
where 1=Monday, 2=Tuesday, ..., 7=Sunday.
With no parameters, use current date.
See also
.Va __DOW__ .
.It @epoch@
Unix epoch time, the number of non-leap seconds which
have passed since 00:00:00\ UTC on Thursday, 1\ January\ 1970.
See section
.Sx Dates and Times .
.It @executable PROGRAM@
Return expanded path to PROGRAM, printing a warning if program is not found.
Variant
.Ql @sexecutable@
does not print a warning.
See also
.Va canrun() .
.It @expr MATH@
Evaluate and print mathematical expression.
Variant
.Ql @sexpr@
performs the same calculations but does not output the result.
However, assignments are still performed and
.Va __EXPR__
is still set.
.It @format FMT [ARG ...]@
.\" Six is entirely arbitrary, limited only by my patience
.\" for repeatedly typing printf()'s for cases that will likely
.\" never be used.  If you need monster @format ...@, go for it!
Print up to five parameters (args 2..6),
using the first argument as a format specification for
.Fn sprintf .
Arguments must be compatible with format string,
otherwise you get to keep all the pieces.
.It @getenv VAR@
Get value of environment variable
.Va VAR .
An error is thrown if
.Va VAR
is not defined.
To ignore error and continue with empty string, disable
.Va __STRICT__[env]
or use variant
.Ql @sgetenv@ .
.It @gregdate MJD@
Print the date corresponding to Modified Julian Day MJD.
The output format is always "YYYY\-MM\-DD" (__FMT__[date] is not used).
See also
.Va @mjd@ .
.It @ifdef{SYMBOL}{TRUE_TEXT}{FALSE_TEXT}@
If SYMBOL is defined, return TRUE_TEXT, else return FALSE_TEXT.
The {FALSE_TEXT} clause is optional, and defaults to the empty string.
.It @ifelse{arg1}{arg2}{arg3}{arg4}...@
@ifelse@ takes three or more arguments.
If the first argument is equal to the second, then the value is the
third argument.
If not equal, and if there are more than four arguments, then the
process repeats with arguments 4, 5, 6, and 7.
Otherwise, the value is either the fourth argument if present, or null
if omitted.
All arguments must appear on the same line.\" Unfortunately!
This baroque arrangement is modeled after
.Xr m4 1 .
For a saner syntax, try the @case or @if commands.
However, @ifelse@ is a function, not a command, so it can be used
in-line with other text, whereas @if and @case cannot.
.It @ifx{BOOL_EXP}{TRUE_TEXT}{FALSE_TEXT}@
Evaluate BOOL_EXP; if True, return TRUE_TEXT else return FALSE_TEXT.
All three brace-enclosed clauses must be present.
Resulting text is again processed for macro substitutions.
@ifx stands for "IF <eXpression>".
.It @ifndef{SYMBOL}{TRUE_TEXT}{FALSE_TEXT}@
If SYMBOL is
.Em not
defined, return TRUE_TEXT, else return FALSE_TEXT.
The {FALSE_TEXT} clause is optional, and defaults to the empty string.
.It @index SYM SUBSTR@
Return the position of SUBSTR within the value of SYM.
Note that
.Nm
follows the Awk convention of numbering characters in a string from 1;
this is different from m4, which is zero-based.
If SUBSTR is not found, the returned value is 0.
.It @join LIS [FS]@
Concatenate each element of LIS into a single string,
inserting FS between elements to separate them.
If FS is omitted, then the value of
.Va __FS__
is used;
if not defined, then a single space shall be the separator.
Variant
.Ql @sjoin@
adds a final FS after the last element (useful when
.Va __FS__
is a newline).
See also
.Va @split .
.It @lc SYM@
Lower case.
.It @left SYM [N]@
Substring of SYM from 1 to Nth character.
.It @len SYM@
Number of characters in SYM's value.
.It @ljust SYM [WIDTH]@
Left-justify the value of SYM in a field of WIDTH columns.
If WIDTH is omitted, the value of
.Va __COLUMNS__
is used.
Strings longer than WIDTH are truncated as necessary.
Variant
.Ql @sljust@
does not truncate output.
.It @ltrim SYM@
Remove leading whitespace.
.It @mid SYM BEG [LEN]@
Substring of SYM from BEG, LEN chars long.
Also called
.Ql @substr@ .
BEG begins the string at position 1.
.It @mjd [YEAR MONTH DAY]@
Return the Modified Julian Day, which is
the number of days since midnight on November\ 17, 1858.
Without parameters, the current date is used.
See also
.Va @gregdate@ .
.It @ord SYM@
Output ASCII code of first character in SYM.
.It @rem COMMENT@
Embedded comment text is ignored.
Variant
.Ql @srem@
also discards preceding whitespace.
.It @right SYM [N]@
Substring of SYM from N to last character.
.It @rjust SYM [WIDTH]@
Right-justify the value of SYM in a field of WIDTH columns.
If WIDTH is omitted, the value of
.Va __COLUMNS__
is used.
Strings longer than WIDTH are truncated as necessary.
Variant
.Ql @srjust@
does not truncate output.
.It @rot13 SYM@
Output value of SYM (or literal string if SYM not defined) with rot13 text.
.It @rtrim SYM@
Remove trailing whitespace.
.It @space [N]@
Output N (default 1) space characters, ASCII 0x20.
Also called
.Ql @spaces@ .
.It @strftime FMT@
Current date/time in user-specified format.
.It @tab [N]@
Output N (default 1) tab characters, ASCII 0x09.
Also called
.Ql @tabs@ .
.It @time@
Current time (format as __FMT__[time]).
See section
.Sx Dates and Times .
.It @trim SYM@
Remove both leading and trailing whitespace.
.It @tz@
Time zone name (format as __FMT__[tz]).
See section
.Sx Dates and Times .
.It @uc SYM@
Upper case.
.It @utc@
Current timestamp in UTC time zone, displayed in ISO\ 8601 format
(format as __FMT__[utc]).
.It @uuid@
UUID (Universally Unique Identifier) version 4, such as
c3525388\&-e400\&\-43a7\&-bc95\&\-9df5fa3c4a52.
.It @xbasename SYM@
Base (file) name of SYM determined by external program.
.It @xdirname SYM@
Directory name of SYM determined by external program.
.El
.Pp
Symbols can be suffixed with "[<key>]" to form simple arrays.
.Ss Dates and Times
.Va __DATE__ ,
.Va __EPOCH__ ,
.Va __TIME__ ,
.Va __TIMESTAMP__ ,
and
.Va __TZ__
are fixed at program start and do not change.
.Ql @date@ ,
.Ql @epoch@ ,
.Ql @time@ ,
and
.Ql @tz@
do change to reflect the current time and date.
Of course, time zones don't normally change; the difference is that
.Ql @__TZ__@
prints
.Qq \-0800
while
.Ql @tz@
prints
.Qq PST .
.Pp
.Em Example :
.Bd -literal -offset indent -compact
@define timestamp @date@T@time@@__TZ__@
@timestamp@
\ \ \ => 1945\&\-07\&\-16T05:30:00\&\-0600
.Ed
.Ss Streams and Diversions
Instead of printing lines immediately to standard output,
the stream of text can be
.Qq diverted
to a temporary buffer area.
Later, you can choose whether to print that diverted text,
write it to an ASCII file, or discard it entirely.
.Nm
attempts to follow m4 in its use of
.Ql @divert
and
.Ql @undivert .
Each stream is identified by its number, a non-negative integer.
Unlike traditional m4 which limits you to nine streams, m2 streams are
created as needed without a pre-determined limit.\" beyond Awk's memory capacity, that is
Stream 0 is interpreted as resuming printing to standard output.
Text diverted to a negative stream is discarded.
The current stream number is available in the system symbol
.Va __DIVNUM__ .
.Bl -inset
.It Em Divert :
No error message or action if argument is not an integer.
.Bl -tag -width @undivert_-1____ -compact -offset indent
.It @divert
Same as
.Ql @divert 0
.It @divert \-1
All subsequent output is discarded.
.It @divert 0
Resume normal output: all subsequent output is sent
to standard output (aka stream # 0).
.It @divert N
All subsequent output is sent to stream N.
.It @divert N1 N2...
Error!  Multiple arguments are not allowed.
.El
.It Em Undivert :
After a stream has been undiverted, it is implicitly cleared.
.Bl -tag -width @undivert_-1____ -compact -offset indent
.It @undivert
Inject all diversions, in numerical order, into the current stream.
.It @undivert \-1
No effect.
.It @undivert 0
No effect.
.It @undivert N
Inject only stream N into the current stream.
.It @undivert N1 N2...
Inject all specified diversions (in argument order, not numerical
order), into current stream.
.It @undivert N FILE
As an extension to m4's undivert, m2 allows you to
output a stream's collected text directly to a file.
Only one stream number may be specified this way.
This form is only available at standard security level.
.El
.It Em Example :
.br
.Bd -literal -offset indent -compact
@divert 1
world!
@divert
Hello,
\ \ \ => Hello,
\ \ \ => world!
.Ed
.Pp
You can determine if a stream buffer contains text by using the function
.Ql @divlines N@ ,
which returns the number of lines stored in a diversion.
This allows the user to alter processing depending on the availability
of text in a stream.
.It Em End-of-Data Processing :
There is an implicit
.Ql @divert 0
and
.Ql @undivert
performed when
.Nm
reaches the end of its input.
If you want to avoid this and discard any diverted data that has not
shipped out yet, add the following to the end of your input data:
.Bd -literal -offset indent -compact
@divert \-1
@undivert
.Ed
This is the tried-and-true, vanilla m4 way of discarding diverted data.
GNU m4 and
.Nm
implement a
.Ql @cleardivert
command which performs a similar operation.
Like
.Ql @undivert ,
with no arguments, it clears all diverted streams.
.Pp
Diverted text will not be processed if m2 exits due to
.Ql @error
or
.Ql @exit
(non-zero status) commands.
However, commands specified with
.Ql @wrap
.Em are
still processed, regardless of exit status.
.El
.Ss Sequences
.Nm
supports named sequences, which are integer values.  By default,
sequences begin at 0 and increment by 1 as appropriate.  These
defaults can be changed, and the value can be updated or restarted.
You create and manage sequences with the
.Ql @sequence <ID> <ACTION> [<ARG>]
command.
Valid actions are:
.Pp
.Bl -tag -width ID_format_STR____ -compact -offset indent
.It ID [create]
Create a new sequence named ID
.It ID delete
Destroy sequence named ID
.It ID format STR
Format string used to print value (%d)
.It ID next
Increment value (no output)
.It ID prev
Decrement value (no output)
.It ID restart
Set current value to initial value
.It ID setincr N
Set increment to N (1)
.It ID setinit N
Set initial value to N (0)
.It ID setval N
Set value directly to N
.El
.Pp
To use a sequence, surround the sequence ID with
.Qq @
characters just like a macro.
This injects the current value, formatted by calling
.Fn sprintf
with the specified format.
The form
.Ql @++ID@
is used to generate an increasing sequence of values printed in a
user-customizable format.
Use
.Ql ++
as shown to increment the sequence value; use
.Ql --
to decrement.
These operators can be used in either a prefix or postfix position.
To get the current value printed in
decimal without modification or formatting, say
.Ql @ID currval@ .
.Pp
Sequence values can be modified in three ways:
.Bl -enum
.It
The
.Ql @sequence
command actions
.Ic next ,
.Ic prev ,
.Ic restart ,
and
.Ic setval
will change the value as specified without generating any output.
.It
Used inline,
.Qq ++
or
.Qq --
(prefix or postfix) will automatically
modify the sequence while outputting the desired value.
.It
The form
.Ql @ID nextval@
will increment the value and return it in decimal without special formatting.
.El
.Pp
.Em Example :
.Bd -literal -offset indent -compact
@sequence counter create
@sequence counter format # %d=
@++counter@ First header
@++counter@ Second header
\ \ \ => # 1=First header
\ \ \ => # 2=Second header
.Ed
.Ss Arrays and Lists
User arrays must be declared before use
by executing the command
.Ql @array
and specifying the name of the array to create.
After array declaration, its elements can be accessed
by using the array name immediately followed by the
element key in brackets; as always, surrounded by
.Qq @ .
Accessing the bare array name, without brackets,
as in
.Ql @ARRAY@ ,
will return the number of elements in the array.
.Pp
Arrays are loaded with data by the
.Ql @data
or
.Ql @filedata
commands.
.Ql @data
requires the data to be present in\-line
in the input file, which is read until
.Ql @enddata .
If you wish to read your data from an external
file, use
.Ql @filedata .
Data loaded in this way are assigned integer
keys from 1 to the number records.
Lists can also be created with
.Ql @split .
.Ss Mathematical Expressions
The
.Ql @expr ...@
function evaluates mathematical expressions and
inserts their results.
.Ql @expr@
supports the standard arithmetic operators:
.Dl (\ \ )\ \ +\ \ \-\ \ *\ \ /\ \ %\ \ ^
and the comparison operators:
.Dl <\ \ <=\ \ ==\ \ !=\ \ >=\ \ >
and return 0 or 1 as per Awk.
Logical negation is available with
.Qq \&! .
No other boolean operators are valid.
.Qq &&
and
.Qq ||
are
.Em not supported !
.Po
However, see section
.Sx Boolean Expressions .
.Pc
.Pp
.Ql @expr@
supports the following functions:
.Pp
.Bl -tag -width defined(sym)____ -compact -offset indent
.It abs(x)
Absolute value of x, |x|
.It acos(x)
Arc-cosine of x, \-1 \*(Le x \*(Le 1
.It asin(x)
Arc-sine of x, \-1 \*(Le x \*(Le 1
.It atan2(y,x)
Arctangent of y/x, \-\*(Pi \*(Le atan2 \*(Le \*(Pi
.It ceil(x)
Ceiling of x, smallest integer \*(Ge x
.It cos(x)
Cosine of x, in radians
.It defined(sym)
1 if sym is defined, else 0
.It deg(x)
Convert radians to degrees
.It exp(x)
Exponential (anti-logarithm) of x, e^x
.It floor(x)
Floor of x, largest integer \*(Le x
.It hypot(x,y)
Hypotenuse of a right-angled triangle
.It int(x)
Integer part of x
.It lg(x)
Logarithm of x, base 2
.It log(x)
Natural logarithm of x, base e
.It log10(x)
Common logarithm of x, base 10
.It max(a,b)
The larger of a and b
.It min(a,b)
The smaller of a and b
.It pow(x,y)
Raise x to the y power, x^y
.It rad(x)
Convert degrees to radians
.It rand()
Random float, 0 \*(Le rand \*(Lt 1
.It randint(x)
Random integer, 1 \*(Le randint \*(Le x
.It round(x)
Normal rounding to nearest integer
.It sign(x)
Signum of x [\-1, 0, or +1]
.It sin(x)
Sine of x, in radians
.It sqrt(x)
Square root of x
.It tan(x)
Tangent of x, in radians
.El
.Pp
.Ql @expr@
will automatically use symbols' and sequences' values in expressions.
Inside
.Ql "@expr ...@" ,
there is no need to surround symbol names
with
.Qq @
characters to retrieve their values.
.Ql @expr@
also recognizes the predefined constants
.Va e ,
.Va pi ,
and
.Va tau .
.Pp
The most recent expression value is automatically stored in
.Va __EXPR__ .
.Ql @expr@
can also assign values to symbols with the
.Qq =
assignment operator.
Assignment is itself an expression, so
.Ql @expr x=5@
assigns the value 5 to
.Va x
and also outputs the result.
To assign a value to a variable without printing, use
.Ql @define .
.Ss Boolean Expressions
Boolean expressions are used in the
.Ql @if
and
.Ql @while
commands and the
.Ql @ifx
function.
They support the
.Qq && ,
.Qq || ,
and
.Qq \&!
operators for logical AND, OR, and NOT, respectively.
The && and || operators will
.Qq short-circuit
and not evaluate their right-hand side terms if the result is
determined by the left-hand side term.
Parentheses may be used to enforce evaluation order.
.Pp
The following boolean predicate functions return either True or False.
Arguments to these functions are scanned for macro expansion.
.Pp
.Bl -tag -width elem_IN_array____ -offset indent
.It canrun(PROGRAM)
True if PROGRAM can be executed; checked with
.Xr sh 1
.Qq "command -v" .
See also
.Va @executable@ .
.It defined(SYMBOL)
True if SYMBOL is defined.
.It env(VAR)
True if variable VAR is defined in process environment.
.It exists(FILE)
True if FILE exists.
.El
.Pp
Another syntax available in a boolean expression is
.Dl elem IN Array | List
which return True if array or list contains elem
and False if not.
Any other expression is evaluated as a mathematical expression and
considered True if the result is non-zero.
.Ss System Symbols
Symbols that start and end with
.Qq __
.Po
like
.Va __FOO__
.Pc
are called
.Qq system
symbols.
Except for certain writable symbols, they cannot be created or modified by the user.
The following are pre-defined; example values, defaults, or types are shown:
.Pp
.Bl -tag -width __FMT__[number]___ -offset indent
.It __COLUMNS__
Width of terminal screen, in characters.
Value from environment variable
.Va COLUMNS ;
if not present, fetch
.Qq cols
value from
.Xr tput 1 .
If security level prevents this, use default value of 80.
User modifiable.
.It __CWD__
Current working directory, including trailing slash.
.It __DATE__
m2 run start date as
.Em YYYYMMDD
(eg: 19450716).
See section
.Sx Dates and Times .
.It __DEBUGFILE__
File path for debug and trace output (user modifiable, default
.Pa /dev/stderr ) .
.It __DEBUG__
Debugging enabled? (boolean, user modifiable, default FALSE).
.It __DIVNUM__
Current stream number.
0, the default value, indicates output to the terminal (standard output).
.It __DOW__
Abbreviated weekday name (Sun, Mon, Tue, etc).
See also
.Va @dow@ .
.It __EPOCH__
Seconds since Epoch at m2 run start time.
See section
.Sx Dates and Times .
.It __EXPR__
Value from most recent @expr ...@ result.
.It __FILE_UUID__
UUID unique to this file.
.It __FILE__
Current file name.
.It __FMT__[date]
Date format for @date@.
Default is "%Y\&-%m\&-%d"; user modifiable.
.It __FMT__[number]
Format for printing numbers (sync w/CONVFMT); user modifiable.
.It __FMT__[seq]
Format for printing sequence values.
Default is "%d"; user modifiable.
.It __FMT__[time]
Time format for @time@.
Default is "%H:%M:%S"; user modifiable.
.It __FMT__[tz]
Time format for @tz@.
Default is "%Z"; user modifiable.
.It __FMT__[utc]
Date format for @utc@.
Default is "%Y\&-%m\&-%dT%H:%M:%S%z"; user modifiable.
.It __FMT__[0]          \" bracket 0
Text output when @boolval@ is False.
Default is "0"; user modifiable.
A Fortran programmer might change this to
.Qq .FALSE.
while a Lisp programmer might change this to
.Qq nil .
.It __FMT__[1]          \" bracket 1
Text output when @boolval@ is True.
Default is "1"; user modifiable.
A Fortran programmer might change this to
.Qq .TRUE.
while a Lisp programmer might change this to
.Qq t .
.It __FS__
If defined, value to use as field separator for
.Ql @split
and
.Ql @join@ .
User modifiable.
.It __GID__
Group id (effective gid).
.It __HOME__
User's home directory, including trailing slash.
.It __HOSTNAME__
FQDN host name (eg myhost.example.com).
.It __HOST__
Short host name (eg myhost).
.It __INPUT__
The data read by @input; user modifiable.
.It __LINE__
Current line number inside
.Va __FILE__ .
.It __M2_UUID__
UUID unique to this m2 run.
.It __M2_VERSION__
m2 version.
.It __NFILE__
Number of files processed so far (e.g., 2).
.It __NLINE__
Number of lines read so far from all files.
.It __OSNAME__
Operating system name.
.It __PID__
m2 process id.
.It __PROG__[...]
Paths to various system utility programs.
.It __SECURE__
Security level (0, 1, or 2).
See
.Sx SECURITY CONSIDERATIONS
for further information.
.It __STRICT__[bool]
If True (the default), it is an error to pass an undefined symbol to
.Ql @boolval@ .
If non-strict (False), undefined variables are considered False.
User modifiable.
.It __STRICT__[def]
If True (the default), symbols inside
.Qq @
signs must be defined.
If non-strict (False),
.Ql @XLERB@
or other unrecognized text will ship out unmodified.
User modifiable.
.It __STRICT__[env]
If True (the default), environment variables must be defined.
If non-strict (False), unknown environment variables expand to an empty string.
(This action can also be accomplished in strict mode with @sgetenv@.)
User modifiable.
.It __STRICT__[file]
If True (the default), reading a non-existent file with
.Ql @include
causes an error.
If non-strict (False), attempts to read non-existent files result in a warning message.
For completely silent behavior, use
.Ql @sinclude .
User modifiable.
.It __STRICT__[key]
If True (the default), it is an error to specify a non-existent key when
indexing an array or list.
If non-strict (False), reading a non-existing index will return the
empty string.
.It __STRICT__[name]
If True (the default), symbol names are limited to the following syntax for names:
.Dl /^[A\-Za\-z#_][A\-Za\-z#_0\-9]*$/
If non-strict (False), symbol names are much more liberal.
User modifiable.
.It __SYNC__
Frequency to flush output (0..2).
0=End only, 1=Every file (default), 2=Every line.
User modifiable.
.It __SYSVAL__
Exit status of most recent @shell or @syscmd command.
.It __TIMESTAMP__
ISO 8601 timestamp, with "T" separator.
See section
.Sx Dates and Times .
.It __TIME__
m2 run start time as
.Em HHMMSS
(eg 053000).
See section
.Sx Dates and Times .
.It __TMPDIR__
Location for temporary files.
Default is /tmp/; user modifiable.
.It __TRACEMODE__
String containing trace control flags.
Default is
.Qq ae .
.It __TRACE__
If True, tracing is enabled.
If False (the default), tracing messages are inhibited
regardless of the settings in
.Va __TRACEMODE__ .
User modifiable.
.It __TZ__
Time zone numeric offset from UTC (\-0800).
See section
.Sx Dates and Times .
.It __UID__
User id (effective uid).
.It __USER__
User name.
.El
.Ss User-Defined Commands
Q.\ What is the difference between
.Ql @define
and
.Ql @newcmd ?
.br
A.\ @define (and @longdef) create a
.Em symbol
whose value can be expanded by surrounding it with "@" characters, as in:
.br
.Bd -literal -offset indent -compact
Hello @name@, I just got a great deal on this new @item@ !!!
.Ed
You can also define and invoke
.Em functions ,
such as
.Ql @getenv@
or
.Ql @ifelse@ ,
which are symbols that may optionally accept parameters.
Symbols and functions can be used in-line with other text and generally
produce or modify output in some way.
.Pp
@newcmd creates a new user
.Em command
which is recognized and executed like other built-in commands (such as
.Ql @if ,
.Ql @define ,
etc).
Commands can only appear on a line of their own
and may or may not produce output.
Their definitions may include complex logic.
.Pp
.Em Example :
.Bd -literal -offset indent -compact
@#              @line{n} produces one data line of the table
@newcmd line{n}
| @format %2d @{n}@ | @format %7.4f @{expr sqrt(n)}@ |
@endcmd
@#              @table prints the entire table
@newcmd table
|  N | sqrt(N) |
|----|---------|
@for N 1 9
@line{@{N}}
@next N
@endcmd
@@
@table
\ \ \ => |  N | sqrt(N) |
\ \ \ => |----|---------|
\ \ \ => |  1 |  1.0000 |
\ \ \ => |  2 |  1.4142 |
\ \ \ => |  3 |  1.7321 |
\ \ \ => |  4 |  2.0000 |
\ \ \ => |  5 |  2.2361 |
\ \ \ => |  6 |  2.4495 |
\ \ \ => |  7 |  2.6458 |
\ \ \ => |  8 |  2.8284 |
\ \ \ => |  9 |  3.0000 |
.Ed
.Ss Debugging
Symbol
.Va __DEBUG__
controls debugging; set it to True or False to enable or disabled debugging messages.
Debugging output is generated by the
.Ql @debug
command and by m2 execution.
The debug file is maintained in symbol
.Va __DEBUGFILE__ .
At security level 0, the user may specify a file path for debugging and tracing output.
At higher security levels, the debug file is forced to
.Pa /dev/stderr ,
which is also the default value.
.Ss Tracing
Tracing an
.Nm
file results in printing additional diagnostic information
to the debug file when certain triggering events occur.
It most frequently happens when a macro is expanded but there are other
possible triggers.
These lines are prefixed with "m2trace:" for easy identification.
System symbol
.Va __TRACE__
provides control over tracing output; nothing will be printed for any
event if its value is False.
Once it is True, tracing output is managed by calling the commands
.Ql @traceon
and
.Ql @traceoff ,
to control which macros will be traced, and
.Ql @tracemode
which controls various options.
.Bl -inset
.It Em Trace On :
Calling
.Ql @traceon
implicitly sets
.Va __TRACE__
to True.
.Bl -tag -width @tracemode_FLAGS___ -compact -offset indent
.It @traceon
Called without arguments, bare
.Ql @traceon
will trace
.Em ALL
symbols, including internal built-ins: it does this by enabling the "t"
option in the trace mode.
.It @traceon SYM ...
Calling
.Ql @traceon
with one or more symbol names will enable tracing for those symbols: it
does this by setting a flag in the name table.
Note that, unlike m4, it is not possible to request tracing for a symbol
that is not defined.
.El
.It Em Trace Off :
.Bl -tag -width @tracemode_FLAGS___ -compact -offset indent
.It @traceoff
Calling
.Ql @traceoff
with no arguments will clear the "t" flag from the trace modes and also set
.Va __TRACE__
to False.
No changes are made to the name table flags.
.It @traceoff SYM ...
Calling
.Ql @traceoff
with one or more symbol names will disable tracing for those symbols by
clearing the name table flag.
It makes no changes to the "t" trace mode nor to
the value of
.Va __TRACE__ .
.El
.It Em Trace Configuration :
Tracing is configured by specifying one or more flag letters, of which
"t" is just one of several.
.Bl -tag -width @tracemode_FLAGS___ -compact -offset indent
.It @tracemode
With no arguments, the trace flags are reset to their default values.
.\"     BSD default = eq
.\"     GNU default = aqe
Currently, the m2 default value is "ae", although this is subject to change.
.It @tracemode [{+|\-}]FLAG...
Otherwise, if the argument consists of the various flag letters shown
below, the value of trace flags is set to the argument, overriding its
previous value.
If the first character is "+" or "\-", then the subsequent letters are
either added to or removed from the existing trace flags; + and \- may be
used repeatedly.
.El
.It Em Flag letters :
These are the only values accepted by
.Ql @tracemode .
Most flags do not alter the value of
.Va __TRACE__ ;
only the T and V flags can change it.
.Pp
These flags control and format trace output:
.Bl -tag -width indent -offset indent
.It f   \" BSD & GNU
Show the current input file name in each trace output line.
.It l   \" BSD & GNU
Show the current input line number in each trace output line.
.It t   \" BSD & GNU
Trace all macro calls.
.It T
When encountered as an unadorned flag letter or with "+",
.Va __TRACE__
is set to True; "\-T" sets it to False.
.El
.Pp
These control macro evaluation tracing:
.Bl -tag -width indent -offset indent
.It a   \" BSD & GNU
Show the actual arguments in each macro call.
This applies to all macro calls if the `t' flag is used, otherwise only
the macros covered by calls of traceon.
This flag is enabled by default.
.\" .It c   \" BSD & GNU
.\" [CURRENTLY NOT IMPLEMENTED]
.\" Show several trace lines for each macro call.
.\" A line is shown when the macro is seen, but before the arguments are
.\" collected; a second line when the arguments have been collected and a
.\" third line after the call has completed.
.It e   \" BSD & GNU
Show the expansion of each macro call, if it is not void.
This applies to all macro calls if the `t' flag is used,
otherwise only the macros covered by calls of traceon.
This flag is enabled by default.
.\" .It q   \" BSD & GNU
.\" [NOT IMPLEMENTED] q option useless to m2 because it has no quote characters
.\" Quote actual arguments and macro expansions in the
.\" display with the current quotes.
.\" .It x   \" BSD & GNU
.\" [CURRENTLY NOT IMPLEMENTED]
.\" Add a unique `macro call id' to each line of the trace output.
.\" This is useful in connection with the `c' flag above.
.El
.Pp
These are for miscellaneous traces:
.Bl -tag -width indent -offset indent
.It i   \" GNU only
Print a message each time the current input file is changed, giving file
name and input line number.
.It p   \" GNU only
Print a message when a named file is found through the path search
mechanism, giving the actual filename used.
.It s   \" m2 extension
Print a message when a symbol is read or written.
.It V   \" BSD & GNU
A shorthand for all of the above flags.
When flags are being set or added,
.Va __TRACE__
is set to True; if flags are being removed, it is not changed.
.El
.El
.Sh IMPLEMENTATION NOTES
.Nm
is written in portable
.Qq standard
Awk and does not require GNU Awk or any other files.
Even later Awk additions such as
.Fn systime
are avoided.
m2 is tested for compatibility with BSD\ Awk version 20210215,
GNU\ Awk 5.3.0, mawk 1.3.4\ 2024012, GoAWK 1.29.1,
and BusyBox Awk\ v1.36.1
.Sh ENVIRONMENT
.Bl -tag -width indent
.It Ev COLUMNS
If available, used to determine the output line width.
.It Ev HOME
Used to access your
.Pa $HOME/.m2rc
file.
Available through symbol
.Va __HOME__ .
.It Ev LOGDIR
Used as an alternative source for
.Va __HOME__
in case
.Va HOME
is not defined in your environment.
.It Ev M2PATH
A colon-separated list of directories to try (if necessary) for the
.Ql @include
and
.Ql @paste
commands.
Note: M2PATH does not apply to the @filedefine or @filedata commands.
.It Ev M2RC
Specifies a file which, if it exists, overrides
.Pa $HOME/.m2rc
.It Ev PWD
If defined, assumed to be user's current directory; otherwise, retrieved
by invoking
.Xr pwd 1 .
Available through symbol
.Va __CWD__ .
.It Ev SHELL
Used as a possible default shell.
.It Ev TMPDIR
Used as a possible temporary directory.
.El
.Sh FILES
.Bl -tag -width indent
.It Xo
.Pa $HOME/.m2rc ,
.Pa ./.m2rc
.Xc
Initialization files are automatically read if available.
If environment variable
.Ev M2RC
exists, its file is read instead of
.Pa $HOME/.m2rc .
To inhibit automatically loading these init files, specify
.Ar init=0
on the command line.
Specifying
.Ar init=1
causes the init files to be loaded (if not done so already)
without the need to specify an input file.
.It Xo
.Pa /dev/stdin ,
.Pa /dev/stdout ,
.Pa /dev/stderr ,
.Pa /dev/tty ,
.Pa /dev/null
.Xc
I/O may be performed on these paths.
.El
.Sh EXIT STATUS
.Bl -tag -width flag -compact
.It Li 0
Normal process completion, or
.Ql @exit
command.
.It Li 1
Internal error generated by Awk error() function.
.It Li 2
User requested
.Ql @error
command in input.
.It Li 66
A file specified on command line could not be read.
.It Li 70
An internal error, not from user code, caused m2 to abend.
.It Li 77
Security violation caused by attempting an operation forbidden
at current
.Va __SECURE__
value.
.El
.Sh EXAMPLES
The following example demonstrates arrays, conditionals, and
.Ql @{...} :
.Bd -literal -offset indent
@#              Use default region if available
@if env(AWS_DEFAULT_REGION)
@define region @getenv AWS_DEFAULT_REGION@
@endif
@#              If you want your own default region, uncomment
@default region us\-west\-2
@#              Otherwise, m2 will exit with error message
@if ! defined(region)
@error You must provide a value for 'region' on the command line
@endif
@#              Validate region
@array valid_regions
@define valid_regions[us\-east\-1]
@define valid_regions[us\-east\-2]
@define valid_regions[us\-west\-1]
@define valid_regions[us\-west\-2]
@if ! @region@ IN valid_regions
@error Region '@region@' is not valid: choose us\-{east,west}\-{1,2}
@endif
@#              Configure image name according to region
@array images
@define images[us\-east\-1]   my\-east1\-image\-name
@define images[us\-east\-2]   my\-east2\-image\-name
@define images[us\-west\-1]   my\-west1\-image\-name
@define images[us\-west\-2]   my\-west2\-image\-name
@define my_image @images[@{region}]@
@#              Output begins here
Region: @region@
Image:  @my_image@
.Ed
.\" .Sh DIAGNOSTICS
.Sh SEE ALSO
.Xr cpp 1 ,
.Xr m4 1
.Bl -hang
.It Lk http://www.drdobbs.com/open-source/m1-a-mini-macro-processor/200001791
.It Lk https://docstore.mik.ua/oreilly/unix3/sedawk/ch13_10.htm
.El
.Rs
.%A Alfred V. Aho
.%A Brian W. Kernighan
.%A Peter J. Weinberger
.%B The AWK Programming Language
.%I Addison-Wesley
.%D 1988
.%O ISBN\ 0\-201\-07981\-X
.Re
.Ss "Other Ms"
.Bl -tag -width M8___ -offset indent
.It M
Admiral Sir Miles Messervy.
.It M1
Jon Bentley's original macro processor, the progenitor of this program.
.Rs
.%A Jon Bentley
.%T m1: A Mini Macro Processor
.%J Computer Language
.%V 7
.%N 6
.%D June 1990
.%P pp. 47\(en61
.Re
.It M2
This program.
.It M3
Kernighan & Plauger's book
.Em Software Tools
describes a macro-processor language which inspired D. M. Ritchie
to write m3, a macro processor for the AP\-3 minicomputer.
Originally, the Kernighan and Plauger macro-processor, and
then m3, formed the engine for the Rational FORTRAN
preprocessor, although it was later replaced with m4.
.Rs
.%A B. W. Kernighan
.%A P. J. Plauger
.%B Software Tools
.%I Addison-Wesley
.%D 1976
.Re
.It M4
From Unix V7, a macro processor
.Dq "intended as a front end for Ratfor, C, and other languages" .
.Rs
.%A B. W. Kernighan
.%A D. M. Ritchie
.%R The M4 Macro Processor
.%Q AT&T Bell Laboratories
.%J Computing Science Technical Report
.%N 59
.%D July 1977
.Re
.It M5
Prof. A. Dain Samples at the University of Cincinnati
described and implemented M5.
.Bd -ragged -offset indent -compact
.Qo
M5 is a powerful, easy to use, general purpose macro language.
M5's syntax allows concise, formatted, and easy to read
specifications of macros while still giving the user control
over the appearance of the resulting text.  M5 macros can have
named parameters, can have an unbounded number of parameters,
and can manipulate parameters as a single unit.
.Qc
.Ed
.Bl -hang -compact
.It Lk https://compilers.iecc.com/comparch/article/92-10-076
.El
.Rs
.%A A. Dain Samples
.%T User's Guide to the M5 Macro Language
.%J m5: macro processor
.%O comp.compilers
.%D October 20, 1992
.Re
.It M5
William A. Ward, Jr., School of Computer and Information Sciences,
University of South Alabama, Mobile, Alabama, also wrote a macro
processor translator (in Awk!) named m5 dated July 23, 1999.
.Bd -ragged -offset indent -compact
.Qo
m5, unlike many macro processors, does not directly
interpret its input.  Instead it uses a two-pass approach
in which the first pass translates the input to an awk
program, and the second pass executes the awk program to
produce the final output.  Macros are defined using awk
assignment statements and their values substituted using
the substitution prefix character ($ by default).
.Qc
.Ed
.It M5
Dr. Richard Daystrom designed and built a multitronic computer
designated M\-5, ca. 2268.
.Qq Not entirely successful.
.It M6
Andrew D. Hall \- M6,
.Bd -ragged -offset indent -compact
.Qo
a general purpose macro processor used to port
the Fortran source code of the Altran computer algebra system.
.Qc
.Ed
.Bl -hang -compact
.It Lk http://man.cat-v.org/unix-6th/6/m6
.It Lk http://cm.bell-labs.com/cm/cs/cstr/2.pdf
.El
.Rs
.%A A. D. Hall
.%R M6 Reference Manual
.%Q Bell Laboratories
.%J Computer Science Technical Report
.%N 2
.%D 1969
.Re
.It M7
G. H. Skillman, Sandra B. Salazar, et al \- M7 is a general purpose
matching filter designed and implemented at the National Bureau of
Standards, ca. 1980.
.Bd -ragged -offset indent -compact
.Qo
M7 is a pattern matching and replacement facility
developed as a UNIX tool for translating and
reformatting queries, languages, and data.  M7 operates
by first preprocessing a set of user defined macros,
then using these macros to match and replace the text in
an input string.  The enabling of the rescan option
directs M7 to match and rematch the macro patterns
against the input string until all possible replacements
have been made.  Three constructions \(em tags, stacks, and
counters \(em allow communication between different macros
and different input strings, to permit such functions as
line numbering, labeling, and argument passing.
.Qc
.Ed
.Bl -hang -compact
.\" The following line has the original, correct link.
.\"   https://www.govinfo.gov/content/pkg/GOVPUB-C13-dd583e065aac7203f7521309ec41220b/pdf/GOVPUB-C13-dd583e065aac7203f7521309ec41220b.pdf
.\" Unfortunately, it causes nroff to generate the warning "can't break line".
.\" To fix, insert a non-printing break point, which makes nroff happy but
.\" the link is no longer technically correct.  (Displayed output is correct.)
.It Lk https://www.govinfo.gov/content/pkg/GOVPUB-C13-\:dd583e065aac7203f7521309ec41220b/pdf/GOVPUB-C13-dd583e065aac7203f7521309ec41220b.pdf
.El
.It M8
A general-purpose preprocessor for metaprogramming
written by Brett Robinson.
.Bd -ragged -offset indent -compact
.Qo
M8 is a command line tool for preprocessing text files.
Its syntax is customizable, and easy to distinguish from
its surrounding text.  Custom macros can be added,
allowing it to be specialized for various uses.  M8
executes macros that match a defined regex, running
either a built-in macro, an external program, or a
remote API, and replaces the call point with the
response string.
.Qc
.Ed
.Bl -hang -compact
.It Lk https://github.com/octobanana/m8
.El
.El
.\" .Sh HISTORY
.Sh AUTHORS
.An Jon Bentley ,
.Mt jlb@research.bell-labs.com
.An Christopher Leyon ,
.Mt cleyon@gmail.com
.\" .Sh CAVEATS
.Sh BUGS
.Nm
is two steps lower than m4.
You'll probably miss something you have learned to expect.
.Pp
Self-referential/recursive macros may hang the program.
.Pp
.Nm
is designed for line-oriented, ASCII text processing.
It is not bullet-proof against all possible input.
For example, some implementations of Awk may not handle data with embedded null
('\\0') characters.
Also, UTF\-8 input has not been tested.
.Pp
Left-to-right order of evaluation is not necessarily guaranteed.
.Dl @++N@ \- We are now on step @N@
may not produce exactly the output you expect.
This is especially noticeable if
.Ql @{...}
is used in complex ways.
.Sh SECURITY CONSIDERATIONS
The symbol
.Ql __SECURE__
contains an integer storing the security level, which controls how
.Nm
may invoke subprocesses.
The default is 0 which signifies no restrictions.
In particular, this allows the
.Ql @shell ,
.Ql @syscmd ,
and
.Ql @esyscmd
commands to attempt execution of any program the user specifies.
Additionally, certain commands may create user-specified external
files, for example by using
.Ql @undivert
or storing a path into symbol
.Va __DEBUGFILE__ .
.Pp
At secure level 1, those commands are disabled entirely.
It also prevents creation of additional files, so
undiverting a stream to an output file is prohibited,
as is specifying a file to receive @dump output.
However, programs required for
.Nm Ap s
operation (as defined in the
.Va PROG
array) are still permitted, since the user cannot modify them and they
are presumably safe to invoke.
.Pp
At level 2, all external programs are prohibited, including those
normally considered safe, such as
.Xr date 1
or
.Xr hostname 1 .
This level will have a detrimental effect on
.Nm Ap s
capabilities, such as disabling
.Ql @time@
et al.
The user may raise the security level, but it cannot be lowered.
